spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_reservation
    username: springboot
    password: springboot
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
logging:
  level:
    root: warn
